import type { IProject } from "@/src/entities/Project";

export const PROJECTS: IProject[] = [
  {
    id: 1,
    title: "LibSpace (Онлайн библиотека)",
    description:
      'Lib Space - курсовая работа на тему "Модель ААА и её имплементация в WEB-приложении". Приложение из себя представляет онлайн библиотеку ВУЗа, где авторизованные пользователи могу брать книги в аренду. В приложении реализованы основные компоненты модели ААА, а именно аутентификация, авторизация и учёт. В приложении есть три роли пользователей: читатели (могу брать книги в аренду), библиотекари (управляют книгами, жанрами и авторами, следят за арендами пользователей) и администраторы (управляют пользователями, следят за их действиями).',
    functional: [
      "Авторизация / Регистрация пользователей (JWT);",
      "Админ панель с возможностями управления сущностями: книг, пользователями, жанрами, авторами, арендами, логами;",
      "Просмотр и фильтрация данных;",
      "Работа с API (REST);",
      "Адаптивная верстка под мобильные устройства;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/lib-space/home.png",
      "/images/projects/lib-space/book.png",
      "/images/projects/lib-space/profile.png",
      "/images/projects/lib-space/register.png",
      "/images/projects/lib-space/login.png",
      "/images/projects/lib-space/borrowings.png",
      "/images/projects/lib-space/dashboard.png",
      "/images/projects/lib-space/404.png",
      "/images/projects/lib-space/filters.png",
      "/images/projects/lib-space/books-table.png",
      "/images/projects/lib-space/book-edit.png",
      "/images/projects/lib-space/book-create.png",
      "/images/projects/lib-space/users-table.png",
      "/images/projects/lib-space/user-create.png",
      "/images/projects/lib-space/user-edit.png",
      "/images/projects/lib-space/genres-table.png",
      "/images/projects/lib-space/genre-create.png",
      "/images/projects/lib-space/genre-edit.png",
      "/images/projects/lib-space/authors-table.png",
      "/images/projects/lib-space/author-edit.png",
      "/images/projects/lib-space/author-create.png",
      "/images/projects/lib-space/borrowings-table.png",
      "/images/projects/lib-space/light.png",
      "/images/projects/lib-space/logs-table.png",
    ],
    tags: [
      "NextJS",
      "TypeScript",
      "Redux Toolkit",
      "ExpressJS",
      "Prisma ORM",
      "Tailwind",
      "shadcn",
      "React",
      "JavaScript",
      "Docker",
      "React Hook Form",
      "Zod",
      "ESLint",
      "Prettier",
      "PostgreSQL",
      "JWT",
    ],
    linkFrontendCode: "https://github.com/dag0S/libspace_frontend",
    linkBackendCode: "https://github.com/dag0S/libspace_backend",
  },
  {
    id: 2,
    title: "42 BROTHERS (Маркетплейс)",
    description:
      "Маркетплейс для стримеров 42-комьюнити, где продавцы могут создавать свои магазины и выкладывать товары. Покупатели могут добавлять товары в избранное и корзину, оплачивать через сервис ЮKassa, оставлять отзывы на товары.",
    functional: [
      "Авторизация / Регистрация пользователей (JWT, Google Auth, Yandex Auth);",
      "Админ панель с возможностями отслеживания статистики магазина и управления всеми сущностями: магазинами, товарами, категориями, цветами;",
      "Просмотр и фильтрация данных;",
      "Работа с API (REST);",
      "Адаптивная верстка под мобильные устройства;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/42-shop/home.png",
      "/images/projects/42-shop/product.png",
      "/images/projects/42-shop/auth.png",
      "/images/projects/42-shop/dashbord.png",
      "/images/projects/42-shop/products.png",
      "/images/projects/42-shop/create-product.png",
      "/images/projects/42-shop/edit-product.png",
      "/images/projects/42-shop/explorer.png",
      "/images/projects/42-shop/cart.png",
      "/images/projects/42-shop/favorites.png",
      "/images/projects/42-shop/profile.png",
      "/images/projects/42-shop/thanks.png",
      "/images/projects/42-shop/categories.png",
      "/images/projects/42-shop/edit-category.png",
      "/images/projects/42-shop/create-category.png",
      "/images/projects/42-shop/colors.png",
      "/images/projects/42-shop/edit-color.png",
      "/images/projects/42-shop/create-color.png",
      "/images/projects/42-shop/reviews.png",
      "/images/projects/42-shop/edit-store.png",
      "/images/projects/42-shop/404.png",
    ],
    tags: [
      "NextJS",
      "NestJS",
      "React",
      "TanStack Query",
      "TypeScript",
      "Redux Toolkit",
      "ЮKassa",
      "Axios",
      "Prisma ORM",
      "Tailwind",
      "shadcn",
      "JavaScript",
      "Docker",
      "React Hook Form",
      "ESLint",
      "Prettier",
      "PostgreSQL",
      "JWT",
    ],
    linkFrontendCode: "https://github.com/dag0S/42-shop-frontend",
    linkBackendCode: "https://github.com/dag0S/42-shop-backend",
  },
  {
    id: 3,
    title: "Auction for streamers (Аукцион для стримеров)",
    description:
      "Аукцион для стримеров с колесом Фортуны. Этот сайт предназначен для взаимодействия между стримером и его аудиторией, позволяя им совместно принимать решения во время стрима. Будь то выбор фильма, сериала или игры для развлечения.",
    functional: [
      "Управление лотами: Возможность добавлять, удалять, обновлять, искать и сохранять лоты в локальном хранилище;",
      "Колесо Фортуны: Определяет победителя в интерактивном режиме;",
      "Таймер: Позволяет устанавливать время для стрима;",
      "Темы: Смена темы приложения (темная/светлая);",
      "Языки: Возможность выбора языка интерфейса;",
      "Адаптивная верстка под мобильные устройства;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/auction/wheel.png",
      "/images/projects/auction/slots.png",
      "/images/projects/auction/winner.png",
      "/images/projects/auction/about.png",
      "/images/projects/auction/404.png",
    ],
    tags: [
      "NextJS",
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Framer Motion",
      "Canvas",
      "Tailwind",
      "shadcn",
      "JavaScript",
      "React Hook Form",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/auction-for-streamers",
    linkLiveDemo: "https://auction-for-streamers.netlify.app/ru",
  },
  {
    id: 4,
    title: "Next pizza (Онлайн пиццерия)",
    description:
      "Интернет магазин пиццерии на NextJS (копия DoDo pizzas). Fullstack веб-приложение полность на NextJS. Оплата через ЮKassa, фильтрация, авторизация (JWT). Отпрвка уведомлений на почту.",
    functional: [
      "Авторизация / Регистрация пользователей (JWT, Google Auth, GitHub Auth);",
      "Уведомления о заказе на почту (Resend);",
      "Оплата корзины через ЮKassa;",
      "Просмотр и фильтрация данных;",
      "Работа с API (REST);",
      "Реализованы истории;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/next-pizza/home.png",
      "/images/projects/next-pizza/product-modal.png",
      "/images/projects/next-pizza/product-page.png",
      "/images/projects/next-pizza/login.png",
      "/images/projects/next-pizza/register.png",
      "/images/projects/next-pizza/cart.png",
      "/images/projects/next-pizza/profile.png",
      "/images/projects/next-pizza/search.png",
      "/images/projects/next-pizza/order.png",
      "/images/projects/next-pizza/story.png",
    ],
    tags: [
      "NextJS",
      "React",
      "TypeScript",
      "Zustand",
      "Resend",
      "ЮKassa",
      "Tailwind",
      "shadcn",
      "JavaScript",
      "React Hook Form",
      "Prisma ORM",
      "PostgreSQL",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/next-pizza",
    linkLiveDemo: "https://next-pizza-six-sepia.vercel.app/",
  },
  {
    id: 5,
    title: "Портфолио 2.0",
    description:
      "Вторая версия моего сайта-портфолио, выполненная на NextJS, React, TypeScript и Framer Motion. На сайте вы можете детально ознакомиться с проектами, с которыми я работал.",
    functional: [
      "Анимация появления секций и объектов на страницах;",
      "Просмотр и фильтрация данных;",
      "Оригинальный дизайн;",
      "Адаптивная верстка под мобильные устройства.",
    ],
    imagesURL: [
      "/images/projects/portfolio-2.0/home.png",
      "/images/projects/portfolio-2.0/projects.png",
      "/images/projects/portfolio-2.0/project.png",
      "/images/projects/portfolio-2.0/about-me.png",
      "/images/projects/portfolio-2.0/contacts.png",
      "/images/projects/portfolio-2.0/404.png",
      "/images/projects/portfolio-2.0/light.png",
    ],
    tags: [
      "NextJS",
      "React",
      "TypeScript",
      "Tailwind",
      "shadcn",
      "Framer Motion",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/portfolio-gosudarev-danila-2.0",
    linkLiveDemo: "https://danila-gosudarev.netlify.app/",
  },
  {
    id: 6,
    title: "Портфолио 1.0",
    description:
      "Мой первый сайт портфолио, в котором были собраны все мои проекты, над которыми я работал. Сайт написан на React и анимирован с помощью Framer Motion.",
    functional: [
      "Анимация появления секций и объектов на страницах;",
      "Просмотр и фильтрация данных;",
      "Оригинальный дизайн;",
      "Адаптивная верстка под мобильные устройства.",
    ],
    imagesURL: [
      "/images/projects/portfolio-1.0/home.png",
      "/images/projects/portfolio-1.0/portfolio.png",
      "/images/projects/portfolio-1.0/project.png",
      "/images/projects/portfolio-1.0/about-me.png",
      "/images/projects/portfolio-1.0/contacts.png",
      "/images/projects/portfolio-1.0/404.png",
    ],
    tags: [
      "React",
      "TypeScript",
      "SASS",
      "Redux Toolkit",
      "Framer Motion",
      "Vite",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode:
      "https://github.com/dag0S/Gosudarev-Danila-Portfolio/tree/master",
    linkLiveDemo: "https://gosudarev-danila.netlify.app/",
  },
  {
    id: 7,
    title: "Tech Wace (Магазин техники)",
    description:
      "Tech Wave интернет-магазин техники, с возможностью авториции, добавления товара в избранное и корзину, фильтрации по категориям, брендам и цене. Реализована смена темы и языка (Русский/English). В качестве сервера используется JSON-sever.",
    functional: [
      "Авторизация / Регистрация пользователей;",
      "Смена темы (Светлая/Темная);",
      "Смена языка (Русский/English);",
      "Добавление товаров в избранное и корзину;",
      "Просмотр и фильтрация товаров;",
      "Работа с API (REST);",
      "Адаптивная верстка под мобильные устройства.",
    ],
    imagesURL: [
      "/images/projects/tech-wave/home.png",
      "/images/projects/tech-wave/product.png",
      "/images/projects/tech-wave/favorites.png",
      "/images/projects/tech-wave/cart.png",
      "/images/projects/tech-wave/login.png",
      "/images/projects/tech-wave/register.png",
      "/images/projects/tech-wave/search.png",
      "/images/projects/tech-wave/profile.png",
      "/images/projects/tech-wave/home-eng.png",
    ],
    tags: [
      "React",
      "TypeScript",
      "SASS",
      "Redux Toolkit",
      "StoryBook",
      "React Router Dom",
      "i18n",
      "Vite",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/tech_wave_frontend",
  },
  {
    id: 8,
    title: "TASK-1 SPA",
    description:
      "Приложение для отображения и взаимодействия с данными из JSONPlaceholder, реализованное с использованием современных технологий фронтенда. Пользователь может просматривать пользователей, посты, альбомы с фотографиями, а также осуществлять поиск и переключение тем.",
    functional: [
      "Смена темы (Светлая/Темная);",
      "Просмотра подробной информации;",
      "Бесконечной прокрутки и пагинации;",
      "Поиск и фильтрация информации;",
      "UI на базе Ant Design;",
      "Адаптивная верстка под мобильные устройства.",
    ],
    imagesURL: [
      "/images/projects/task-1/home.png",
      "/images/projects/task-1/posts-table.png",
      "/images/projects/task-1/post.png",
      "/images/projects/task-1/users-card.png",
      "/images/projects/task-1/users-table.png",
      "/images/projects/task-1/albums.png",
      "/images/projects/task-1/404.png",
    ],
    tags: [
      "React",
      "TypeScript",
      "Ant Design",
      "Redux Toolkit",
      "Axios",
      "React Router Dom",
      "Vite",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/tech_wave_frontend",
  },
  {
    id: 9,
    title: "Voice Tag Lab",
    description:
      "Войс тэг - это незаменимая вещь для каждого битмейкера. И наша команда готова изготовить его именно для тебя. Выбирай любой из наших голосов, и выделяйся!",
    functional: ["Адаптивная верстка под мобильные устройства."],
    imagesURL: [
      "/images/projects/voice-tag-lab/home-min.png",
      "/images/projects/voice-tag-lab/home-full.png",
      "/images/projects/voice-tag-lab/modal.png",
    ],
    tags: ["HTML", "CSS", "SASS", "Vite", "JavaScript"],
    linkFrontendCode: "https://github.com/dag0S/voice-tag-lab",
    linkLiveDemo: "https://warm-seahorse-f0148f.netlify.app/",
  },
  {
    id: 10,
    title: "Lamborghini",
    description:
      "Итальянская компания, производитель спортивных автомобилей под маркой Lamborghini. Данный лендинг информирует о гранд-финале гонок.",
    functional: ["Адаптивная верстка под мобильные устройства."],
    imagesURL: [
      "/images/projects/lambo/home.png",
      "/images/projects/lambo/home-full.png",
    ],
    tags: ["HTML", "CSS", "SASS", "Gulp"],
    linkFrontendCode: "https://github.com/dag0S/Lamborghini/tree/master",
    linkLiveDemo: "https://lamborghini-demo.netlify.app/",
  },
  {
    id: 11,
    title: "Oculus",
    description:
      "Oculus - это очки виртуальной реальности будущего. Данный страница рекламирует данный продукт.",
    functional: ["Адаптивная верстка под мобильные устройства."],
    imagesURL: [
      "/images/projects/oculus/home.png",
      "/images/projects/oculus/home-full.png",
    ],
    tags: ["HTML", "CSS", "SASS", "Gulp"],
    linkFrontendCode: "https://github.com/dag0S/Oculus",
    linkLiveDemo: "https://oculus-demo-1-0-1.netlify.app/",
  },
  {
    id: 12,
    title: "HooBank",
    description:
      "HooBank – инновационный банк. На этом лендинге мы рассказываем о возможностях и фичах этого банка. Сайт создан с использованием React и библиотеки стилей Tailwind.",
    functional: ["Адаптивная верстка под мобильные устройства."],
    imagesURL: [
      "/images/projects/hoo-bank/home.png",
      "/images/projects/hoo-bank/home-full.png",
    ],
    tags: ["Tailwind", "React", "Vite", "ESLint", "Prettier"],
    linkFrontendCode: "https://github.com/dag0S/HooBank",
    linkLiveDemo: "https://genuine-griffin-680248.netlify.app/",
  },
  {
    id: 13,
    title: "LoftHouse",
    description:
      "LoftHouse – это жилой комплекс, расположенный в историческом центре города. Данный одностраничный сайт призван познакомить вас со всеми преимуществами этого места.",
    functional: ["Адаптивная верстка под мобильные устройства."],
    imagesURL: [
      "/images/projects/loft-house/home.png",
      "/images/projects/loft-house/home-full.png",
    ],
    tags: ["HTML", "CSS", "Gulp", "SASS"],
    linkFrontendCode: "https://github.com/dag0S/loft-house",
    linkLiveDemo: "https://loft-house-demo.netlify.app/",
  },
  {
    id: 14,
    title: "D&M Leasing",
    description:
      "D&M Leasing – сайт по приобретению автомобилей, который состоит из нескольких страниц, написанных на чистом HTML и CSS.",
    functional: ["Адаптивная верстка под мобильные устройства."],
    imagesURL: [
      "/images/projects/dm/home.png",
      "/images/projects/dm/home-full.png",
      "/images/projects/dm/cars.png",
      "/images/projects/dm/contacts.png",
    ],
    tags: ["HTML", "CSS", "Gulp", "SASS", "JavaScript"],
    linkFrontendCode: "https://github.com/dag0S/Cars",
    linkLiveDemo: "https://cars-demo-1-0-1.netlify.app/",
  },
];
