export const PROJECTS = [
  {
    id: 1,
    title: "LibSpace (Онлайн библиотека)",
    description:
      'Lib Space - курсовая работа на тему "Модель ААА и её имплементация в WEB-приложении". Приложение из себя представляет онлайн библиотеку ВУЗа, где авторизованные пользователи могу брать книги в аренду. В приложении реализованы основные компоненты модели ААА, а именно аутентификация, авторизация и учёт. В приложении есть три роли пользователей: читатели (могу брать книги в аренду), библиотекари (управляют книгами, жанрами и авторами, следят за арендами пользователей) и администраторы (управляют пользователями, следят за их действиями).',
    functional: [
      "Авторизация / Регистрация пользователей (JWT);",
      "Админ панель с возможностями управления сущностями: книг, пользователями, жанрами, авторами, арендами, логами;",
      "Просмотр и фильтрация данных;",
      "Работа с API (REST);",
      "Адаптивная верстка под мобильные устройства;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/lib-space/home.png",
      "/images/projects/lib-space/book.png",
      "/images/projects/lib-space/profile.png",
      "/images/projects/lib-space/register.png",
      "/images/projects/lib-space/login.png",
      "/images/projects/lib-space/borrowings.png",
      "/images/projects/lib-space/dashboard.png",
      "/images/projects/lib-space/404.png",
      "/images/projects/lib-space/filters.png",
      "/images/projects/lib-space/books-table.png",
      "/images/projects/lib-space/book-edit.png",
      "/images/projects/lib-space/book-create.png",
      "/images/projects/lib-space/users-table.png",
      "/images/projects/lib-space/user-create.png",
      "/images/projects/lib-space/user-edit.png",
      "/images/projects/lib-space/genres-table.png",
      "/images/projects/lib-space/genre-create.png",
      "/images/projects/lib-space/genre-edit.png",
      "/images/projects/lib-space/authors-table.png",
      "/images/projects/lib-space/author-edit.png",
      "/images/projects/lib-space/author-create.png",
      "/images/projects/lib-space/borrowings-table.png",
      "/images/projects/lib-space/light.png",
      "/images/projects/lib-space/logs-table.png",
    ],
    tags: [
      "NextJS",
      "TypeScript",
      "Redux Toolkit",
      "ExpressJS",
      "Prisma ORM",
      "Tailwind",
      "shadcn",
      "React",
      "JavaScript",
      "Docker",
      "React Hook Form",
      "Zod",
      "ESLint",
      "Prettier",
      "PostgreSQL",
      "JWT",
    ],
    linkFrontendCode: "https://github.com/dag0S/libspace_frontend",
    linkBackendCode: "https://github.com/dag0S/libspace_backend",
  },
  {
    id: 2,
    title: "42 BROTHERS (Маркетплейс)",
    description:
      "Маркетплейс для стримеров 42-комьюнити, где продавцы могут создавать свои магазины и выкладывать товары. Покупатели могут добавлять товары в избранное и корзину, оплачивать через сервис ЮKassa, оставлять отзывы на товары.",
    functional: [
      "Авторизация / Регистрация пользователей (JWT, Google Auth, Yandex Auth);",
      "Админ панель с возможностями отслеживания статистики магазина и управления всеми сущностями: магазинами, товарами, категориями, цветами;",
      "Просмотр и фильтрация данных;",
      "Работа с API (REST);",
      "Адаптивная верстка под мобильные устройства;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/42-shop/home.png",
      "/images/projects/42-shop/product.png",
      "/images/projects/42-shop/auth.png",
      "/images/projects/42-shop/dashbord.png",
      "/images/projects/42-shop/products.png",
      "/images/projects/42-shop/create-product.png",
      "/images/projects/42-shop/edit-product.png",
      "/images/projects/42-shop/explorer.png",
      "/images/projects/42-shop/cart.png",
      "/images/projects/42-shop/favorites.png",
      "/images/projects/42-shop/profile.png",
      "/images/projects/42-shop/thanks.png",
      "/images/projects/42-shop/categories.png",
      "/images/projects/42-shop/edit-category.png",
      "/images/projects/42-shop/create-category.png",
      "/images/projects/42-shop/colors.png",
      "/images/projects/42-shop/edit-color.png",
      "/images/projects/42-shop/create-color.png",
      "/images/projects/42-shop/reviews.png",
      "/images/projects/42-shop/edit-store.png",
      "/images/projects/42-shop/404.png",
    ],
    tags: [
      "NextJS",
      "NestJS",
      "React",
      "TanStack Query",
      "TypeScript",
      "Redux Toolkit",
      "ЮKassa",
      "Axios",
      "Prisma ORM",
      "Tailwind",
      "shadcn",
      "JavaScript",
      "Docker",
      "React Hook Form",
      "ESLint",
      "Prettier",
      "PostgreSQL",
      "JWT",
    ],
    linkFrontendCode: "https://github.com/dag0S/42-shop-frontend",
    linkBackendCode: "https://github.com/dag0S/42-shop-backend",
  },
  {
    id: 3,
    title: "Auction for streamers (Аукцион для стримеров)",
    description:
      "Аукцион для стримеров с колесом Фортуны. Этот сайт предназначен для взаимодействия между стримером и его аудиторией, позволяя им совместно принимать решения во время стрима. Будь то выбор фильма, сериала или игры для развлечения.",
    functional: [
      "Управление лотами: Возможность добавлять, удалять, обновлять, искать и сохранять лоты в локальном хранилище;",
      "Колесо Фортуны: Определяет победителя в интерактивном режиме;",
      "Таймер: Позволяет устанавливать время для стрима;",
      "Темы: Смена темы приложения (темная/светлая);",
      "Языки: Возможность выбора языка интерфейса;",
      "Адаптивная верстка под мобильные устройства;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/auction/wheel.png",
      "/images/projects/auction/slots.png",
      "/images/projects/auction/winner.png",
      "/images/projects/auction/about.png",
      "/images/projects/auction/404.png",
    ],
    tags: [
      "NextJS",
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Framer Motion",
      "Canvas",
      "Tailwind",
      "shadcn",
      "JavaScript",
      "React Hook Form",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/auction-for-streamers",
    linkLiveDemo: "https://auction-for-streamers.netlify.app/ru",
  },
  {
    id: 4,
    title: "Next pizza (Онлайн пиццерия)",
    description:
      "Интернет магазин пиццерии на NextJS (копия DoDo pizzas). Fullstack веб-приложение полность на NextJS. Оплата через ЮKassa, фильтрация, авторизация (JWT). Отпрвка уведомлений на почту.",
    functional: [
      "Авторизация / Регистрация пользователей (JWT, Google Auth, GitHub Auth);",
      "Уведомления о заказе на почту (Resend);",
      "Оплата корзины через ЮKassa;",
      "Просмотр и фильтрация данных;",
      "Работа с API (REST);",
      "Реализованы истории;",
      "Оптимизация производительности и SEO.",
    ],
    imagesURL: [
      "/images/projects/next-pizza/home.png",
      "/images/projects/next-pizza/product-modal.png",
      "/images/projects/next-pizza/product-page.png",
      "/images/projects/next-pizza/login.png",
      "/images/projects/next-pizza/register.png",
      "/images/projects/next-pizza/cart.png",
      "/images/projects/next-pizza/profile.png",
      "/images/projects/next-pizza/search.png",
      "/images/projects/next-pizza/order.png",
      "/images/projects/next-pizza/story.png",
    ],
    tags: [
      "NextJS",
      "React",
      "TypeScript",
      "Zustand",
      "Resend",
      "ЮKassa",
      "Tailwind",
      "shadcn",
      "JavaScript",
      "React Hook Form",
      "Prisma ORM",
      "PostgreSQL",
      "ESLint",
      "Prettier",
    ],
    linkFrontendCode: "https://github.com/dag0S/next-pizza",
    linkLiveDemo: "https://next-pizza-six-sepia.vercel.app/",
  },
];
