import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import "../../styles/globals.css";
import { Header } from "@/src/widgets/Header";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Данила Государев | Frontend developer",
  description: "Generated by create next app",
};

const MainLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ru">
      <body className={`${openSans.variable} antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default MainLayout;
